### Health for all ecosystem
GET http://localhost:3000/api/health
Accept: application/json

### Get Example
GET http://localhost:3000/api/v1/rpg/players/72442e30-8643-37d2-a4f5-5b3c94a704a8
Accept: application/json

### Get Example
GET http://localhost:3000/api/v1/rpg/leaderboards?type=kill
Accept: application/json

### Get Example    "primaryGroup": "defa
GET http://localhost:3000/api/v1/rpg/players/72442e30-8643-37d2-a4f5-5b3c94a704a8
Accept: application/json

### Get Example
GET http://localhost:3000/api/v1/rpg/players/72442e30-8643-37d2-a4f5-5b3c94a704a8?type=kill
Accept: application/json

### Get Example
GET http://localhost:3000/api/v1/rpg/players/75b9dbb7-4fe6-3597-bc5b-f20664e05428?type=kill
Accept: application/json


